name: weather_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  go_router: ^13.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  multiple_result: ^5.1.0
  flutter_gen: ^5.3.2 # gennerator for assets
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.4
  flutter_gen_runner: ^5.3.2
  hive_generator: ^2.0.1


flutter_gen:
  output: lib/src/generated/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
